version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - STORYBOOK_DISABLE_TELEMETRY=1
    command: npm run storybook -- --no-open
